### ISSUE TITLE
Feature request: Use DuckDuckGo tracker radar data into Ghostery adblocker

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [cliqz-oss/adblocker#1041]
I already opened multiple issues on this topic explaining it further. Here they are

https://github.com/ghostery/ghostery-extension/issues/575

https://github.com/disconnectme/disconnect-tracking-protection/issues/199

https://github.com/AdguardTeam/AdguardFilters/issues/58396

https://github.com/easylist/easylist/issues/5646

**Comment by a-privacy-conscious-user** [comment]
This screenshots shows some of the fingerprinters that were not blocked by other lists (EasyList and AdGuard did not block some of them) but that appeared on DuckDuckGo tracker radar data sets. Maybe there are more that could be added to more lists

![Captura de Pantalla 2020-07-01 a la(s) 11 09 41](https://user-images.githubusercontent.com/67610240/86253985-9c93c680-bb8b-11ea-89d7-7b4388dff5cf.png)

**Comment by remusao** [comment]
Hey @a-privacy-conscious-user,

Thanks for taking the time to open an issue here. It might make sense to leverage the data from Tracker Radar in some ways in Ghostery, but this should probably be discussed in the `ghostery-extension` repository directly. This repository (`@cliqz/adblocker`) is agnostic to the lists used by projects using the adblocker library, hence it is already possible for consumers of the library to use DuckDuckGo assets if they wish to.

Best,
Rémi
