### ISSUE TITLE
Dependency on @types/puppeteer

### ISSUE THREAD

**Issue by bkniffler** [cliqz-oss/adblocker#1052]
Hey, could you please remove the dependency on @types/puppeteer? If people have their own version of @types/puppeteer installed, like v3.0.0, this is causing some really annoying issues due to multiple versions being installed. I'd suggest moving this to peerDependencies.

Thanks, keep up your great work!

**Comment by remusao** [comment]
Hey @bkniffler,

Thanks for opening this issue. I was hoping that with the migration to TypeScript of puppeteer, the separate types would be deprecated completely soon, but that does not seem to be the case yet (although types are already shipped in the npm package, they are not linked in `package.json`). I guess what you suggest also makes sense, but there are some public functions and methods which require types exported from `@types/puppeteer`, which is why it is a dependency in the first place.

Best,

**Comment by bkniffler** [comment]
Sure, but if any component using (and exporting) @react/types would have that in the dependencies, we'd not have a good dev time due to many conflicts everywhere; that's why peerDependencies exist in the first place. If you really need a specific minimum version, you can still put that into peerDependencies. People who don't need typescript will not bother anyways and people who need typescript will install @types/puppeteer anyways.

Right now, people like me are first getting confusing type errors and when we figure out that some library forces a specific, old version on us, we'll use yarn resolutions or some other more complicated way to fix that.

You can also define `*` as a dependency version, but peerDependencies should really be the way to go.

Cheers!

**Comment by remusao** [comment]
No worries, I have to admit that I am still playing around with these dependencies and it's not always clear to me what the best practice is (especially with @types packages). Having this `@types/puppeteer` in peerDependencies makes sense to me. I guess this means that users of `@cliqz/adblocker-puppeteer` in a TypeScript project will need to also specify `@types/puppeteer` in their package.json, right?

**Comment by bkniffler** [comment]
Exactly, here is a great StackOverflow issue to that exact question btw: 
https://stackoverflow.com/questions/54926369/what-dependency-type-should-types-be-for-a-published-package

**Comment by remusao** [comment]
@bkniffler I have made some changes in https://github.com/cliqz-oss/adblocker/pull/1067 related to this issue, could you maybe check what you think about it? Mainly, I have relaxed the version bounds (`@types/puppeteer` -> `3.x` and `puppeteer` -> `5.x`) and both are now in `peerDependencies`.

**Comment by bkniffler** [comment]
Works great, thanks!
