### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by juanchaur1** [cliqz-oss/adblocker#107]
Hi,

I'm trying to get this work with [puppeteer](https://github.com/GoogleChrome/puppeteer) and the fetch is failing so far.

```bash
There has been an error ReferenceError: fetch is not defined
    at fetchResource (../node_modules/@cliqz/adBlocker/dist/adblocker.cjs.js:3552:5
```

Is there a way to support this in Node?

**Comment by remusao** [comment]
Hi!

Thanks for giving it a shot. I am not sure how you got this error. The way I'm usually running this script: https://github.com/cliqz-oss/adblocker/blob/master/bench/comparison/create_dataset.js is the following:

```sh
$ cd ./bench/comparison/
$ make deps
$ node create_dataset.js
```

Make sure that you have enough memory available as there are by default multiple instances of Chrome running. You can change the size of the pool directly in the code.

Let me know how that works for your, it should run fine in Node.js.

**Comment by juanchaur1** [comment]
Thanks for the feedback!
