### ISSUE TITLE
Error: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by DemGiran** [cliqz-oss/adblocker#1193]
How to handle this error? I am creating multiple pages each page initialized with the adblocker to do some work and then I subsequently remove the page. I get this error when I remove the page.

Using the playwright example

**Comment by remusao** [comment]
Hello,

I think it would be helpful to provide some code snippet so that I can try to reproduce locally. Are you calling `disableBlockingInPage` on each page before you destroy them? Do you maybe have a stacktrace?

Best,

**Comment by remusao** [comment]
I'm gonna close this one for inactivity. Feel free to reopen if you still encounter the issue.

**Comment by lucasassisrosa** [comment]
Stumbled into the same issue. My solution was avoid closing the context right away. I either gave some time before killing/moving forward with the execution, or used a new tab for checks, without removing the page. See https://stackoverflow.com/questions/56345544/trouble-clicking-on-different-links-using-puppeteer/56349839#56349839
