### ISSUE TITLE
[Question] How to use with Puppeteer

### ISSUE THREAD

**Issue by Kikobeats** [cliqz-oss/adblocker#123]
Hello,

First of all, thanks for creating this awesome project!

I'm trying to leverage adblock capabilities into my Puppeteer code.

Basically, puppeteer allows you abort requests, so just the thing I need is to determinate if an ad request should be aborted.

As a reference, that's my current implementation for aborting tracking requests: https://github.com/Kikobeats/browserless/blob/master/packages/goto/src/index.js#L46

If I read docs correctly, I need to create a `FiltersEngine` instance and check for `match` property.

Something like this can replace the previous code:

```js
if (abortTrackers) {
      const { match } = engine.match(req)
      if (match) {
        debug(`abort:tracker:${++reqCount.abort}`, resourceUrl)
        return req.abort()
      }
    }
```

I created a `FilterEngine` instance providing a bit rules file, as a result of concatenating the most popular rules list (easylist, etc).

I'm not sure if I'm using the wrong API method, but the point is it never match the rule, even I try with sites I know it needs to match since I have the same rules on the browser 🤔 

I suppose the thing is wrong is because `req` [from Puppeteer](https://github.com/GoogleChrome/puppeteer/blob/v1.14.0/docs/api.md#class-request) is not the same than your `Request` object? not sure

Any idea about what is happening is welcome 😅

**Comment by remusao** [comment]
Hi @Kikobeats,

Thanks for consider this project for `browserless`! I think you should be able to make it work with puppeteer in the following way:

```js
import { FiltersEngine, makeRequest } from '@cliqz/adblocker';
import { parse } from 'tldts';

// Lists can be loaded from files or fetched from remote (e.g.:
// https://github.com/cliqz-oss/adblocker/blob/master/src/fetch.ts#L14)
const list = `
! First lines of easylist.txt
&act=ads_
&ad.vid=$~xmlhttprequest
&ad_box_
&ad_channel=
&ad_classid=
! ...
`;

// Initialize adblocker using `list`, a string containing all filters.
// You can use easylist.txt or multiple lists concatenated. Here
// we specify that we are not interested in loading so-called cosmetics
// (the filters which can be used to apply custom stylesheets as well as
// injecting scripts in pages directly). This makes sure we only keep in
// memory the rules needed for network filtering.
const engine = FiltersEngine.parse(list, { loadCosmeticFilters: false });

// Mapping from puppeteer request types to adblocker. This is needed because not all
// types from puppeteer have the same name as the webRequest APIs from browsers
// (which the adblocker expects). I took the full list of types from this documentation:
// https://github.com/GoogleChrome/puppeteer/blob/v1.14.0/docs/api.md#requestresourcetype
const types = {
  document: 'main_frame',
  eventsource: 'other',
  fetch: 'xhr',
  font: 'font',
  image: 'image',
  manifest: 'other',
  media: 'media',
  other: 'other',
  script: 'script',
  stylesheet: 'stylesheet',
  texttrack: 'other',
  websocket: 'websocket',
  xhr: 'xhr',
};

// Match a puppeteer request. The important part here is to create a `Request`
// object which contains the information needed to match against the rules.
// This is achieved by calling `makeRequest` on a `url`, an optional `sourceUrl` and
// the `type` of the request (e.g.: script or image). We also need to provide a `parse`
// function to extract both a hostname and a domain from each URL. We use `tldts`
// here which provides this method and allows parsing the URLs efficiently and accurately.
// The type of this function should be:
// function parse(url: string): { domain: string, hostname: string } {
//   return { domain, hostname };
// }
const { match } = engine.match(
  makeRequest(
    {
      sourceUrl: request.frame().url(),
      type: types[request.resourceType()],
      url: request.url(),
    },
    parse,
  ),
);

// Here `match` will be true or false depending on if the request should be blocked
// or not. The result of `engine.match` contains extra information which can be
// handy in some contexts:
// https://github.com/cliqz-oss/adblocker/blob/master/src/engine/engine.ts#L412
```

Let me know if that works for you!
Rémi

**Comment by Kikobeats** [comment]
Thanks for the reply – so much interesting!

Are your default list/rules a selection based on criteria? 

Personally, I'm using the following list of rules

```
const FILTERS = [
  // uBlock Origin –  https://github.com/uBlockOrigin/uAssets/tree/master/filters
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt',
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt',
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt',
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt',
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt',
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt',

  // Easylist – https://easylist.to/
  'https://easylist.to/easylist/easylist.txt',
  'https://easylist.to/easylist/easyprivacy.txt',
  'https://easylist.to/easylist/fanboy-annoyance.txt',
  'https://easylist.to/easylist/fanboy-social.txt',

  // Other
  'http://pgl.yoyo.org/as/serverlist.php?hostformat=adblockplus;showintro=0&mimetype=plaintext',
  'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/recipes/recipes_en.txt',
  'https://www.i-dont-care-about-cookies.eu/abp/',
  'https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt',
  'https://gnuzilla.gnu.org/filters/blacklist.txt'
]
```

They are basically uBlock easy mode + annoying cookies banner.

As you pointed `CosmeticFilters` are also interested, my main user case is removing ads before take a screenshot

**Comment by Kikobeats** [comment]
I published my wip branch, just if you want to take a look
https://github.com/Kikobeats/browserless/pull/32 🙂

**Comment by remusao** [comment]
Hey @Kikobeats,

> Are your default list/rules a selection based on criteria?

The default lists in the repository are a conservative selection of filters which target exclusively ads. In fact, this list is not used in production and simply meant for testing purposes at the moment, as well as to allow an easier integration with the example webextension contained in this repository. It is expected that users of the library will provide their own lists, according to their own constraints and use-case.

> Personally, I'm using the following list of rules

The lists you selected looks good and I think it should work fine with the library. The only exception is `https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/recipes/recipes_en.txt` which is a different kind of ruleset targeted at the uMatrix extension. I am not very familiar with this format but maybe support could be added to the library in the future.

> In that case, should I inject script/style as Frame or as part of the page?

I would suggest to inject the cosmetics in every frame. The first frame you will see from the `frameattached` event should be the main document frame (which would corresponds to the `page` injection you mentioned). The main frame is indeed the most important one, but if it does not add extra complexity, I think it would be useful to process all frames this way.

> PS: I published my wip branch, just if you want to take a look Kikobeats/browserless#32 slightly_smiling_face

Thanks! That looks great. I would be happy to have a look when it's ready if you think that could help the project.

Have a nice day,
Rémi

**Comment by Kikobeats** [comment]
I released a browserless goto first version without cosmetic filters, I want to explore it a bit and include it in the next version.

Thanks for all the feedback! 🙂

**Comment by Kikobeats** [comment]
Hello, @remusao 

After a time running the adblocker I feel the impact of it in my product is very positive. Thanks a lot help me integrate with Puppeteer 🙂.

I'm experimenting an error (https://sentry.io/share/issue/b8f60212eaea433282ab7d1f21b2f18e/) and I want to know your opinion to the best way to handle it.

The point is, sometimes `req.frame().url()` can't be obtained, Should I avoid call `makeRequest` in that case? 🤔 

current code:

``        makeRequest(
          {
            type: webRequestType(resourceType),
            sourceUrl: req.frame().url()
            url: resourceUrl
          },
          url => tldts.parse(url)
        )

```

expected

```
if (req.frame && req.frame().url()) {
        makeRequest(
          {
            type: webRequestType(resourceType),
            sourceUrl: req.frame().url()
            url: resourceUrl
          },
          url => tldts.parse(url)
        )
}
```

**Comment by remusao** [comment]
Hi @Kikobeats,

Very happy to hear that the adblocker is working well for your project!

Regarding the error, `makeRequest` should already be able to accommodate with an undefined `sourceUrl`. I think the error you encounter here is due instead to `req.frame()` returning `null`, so you cannot call `(null).url()`, which raises the exception. Maybe the following change would solve the issue?

```js
const frame = req.frame();
makeRequest({
    type: webRequestType(resourceType),
    sourceUrl: frame !== null ? frame.url() : undefined,
    url: resourceUrl
}, url => tldts.parse(url))
```

Let me know if that works!
