### ISSUE TITLE
adblock-electron filterlist rule ##+js( not returning any scripts to execute

### ISSUE THREAD

**Issue by jollySwag** [cliqz-oss/adblocker#1337]
As the title says, 

const { active, styles, scripts } = this.getCosmeticsFilters({...}) in @cliqz/adblocker-electron/dist/cjs/adblocker.js isn't returning any matching scripts when it matches a code rule.

An example of the "msg" recieved by this.onGetCosmeticFilters = (event, url, msg):
```
{ classes:
   [  'col-xs-8',
     'ng-binding',
     'col-xs-4',
     'language-bash',
     'language-cpp'],
  hrefs:
   [ 'http://helloworld.org/#codepart0-0',
     'http://helloworld.org/data/helloworld.b',
     'http://en.wikipedia.org/wiki/B_(programming_language)',
     'http://helloworld.org/#codepart0-1',
     'http://helloworld.org/data/helloworld',
     'http://en.wikipedia.org/wiki/Bash_(Unix_shell)',
     'http://helloworld.org/#codepart0-2',
     'http://helloworld.org/data/helloworld.bf',
     'http://en.wikipedia.org/wiki/Brainfuck',
     'http://helloworld.org/#codepart3-0',
     'http://helloworld.org/data/helloworld.c',
     'http://en.wikipedia.org/wiki/C_(programming_language)',]
  ids:
   [ 'item0-0',
     'codepart0-0',
     'item0-1',
     'codepart0-1',
     'item0-2',
     'codepart0-2']
}
```
Please note the above is not the full contents of msg.

For this i used a test rule to try and trigger it:

> helloworld.org/##+js(noeval)

Also, besides installing the package, i haven't downloaded any additional resources and the Blocker engine is just loading the list locally rather than fetching. Using ElectronBlocker.parse(rules);

 I would be very appreciative if i could get some help with this.

**Comment by remusao** [comment]
Hi @jollySwag,

Thanks for taking the time to open an issue. If I understand correctly you are initializing the blocker from a list of custom rules using `.parse(...)`. One of these rules (i.e. `helloworld.org/##+js(noeval)`) relies on a `resource`. These need to be loaded independently to be accessible. Here is a self-contained example:

```
const { ElectronBlocker, fetchResources } = require('@cliqz/adblocker-electron');
const fetch = require('node-fetch');

(async () => {
  const blocker = ElectronBlocker.parse('helloworld.org##+js(noeval)');

  // Load resources
  const resources = await fetchResources(fetch);
  blocker.updateResources(resources, `${resources.length}`);

  console.log(blocker.getCosmeticsFilters({
    url: 'https://helloworld.org/',
    hostname: 'helloworld.org',
    domain: 'helloworld.org',
  }));
})();
```

Also, the filter should be `helloworld.org##+js(noeval)` (without a slash after `helloworld.org`).

**Comment by jollySwag** [comment]
Excellent that's worked, thank you for your help.
