### ISSUE TITLE
Getting the list of blocked trackers and ads 

### ISSUE THREAD

**Issue by dud3** [cliqz-oss/adblocker#1423]
I'm trying to use the adblocker in Puppeteer, is there a way of getting the list of blocked trackers and ads?

Thank you.

**Comment by remusao** [comment]
Hi @dud3,

Yes there is (but I just realized that this is not well documented at all!). The blocker instance exposes multiple events that you can listen to such as `request-blocked`. You can find an example of usage here: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts#L32

```js
blocker.on('request-blocked', (request) => {
  console.log('blocked', request.url);
});
```

Best,

**Comment by dud3** [comment]
Thank you.

**Comment by remusao** [comment]
Closing this, feel free to reopen and comment if I can help you with anything else.
