### ISSUE TITLE
MemoryLeak in PuppeteerExtraPluginAdblocker library

### ISSUE THREAD

**Issue by victornpb** [cliqz-oss/adblocker#1449]
I reported an issue in a dependant library https://github.com/berstend/puppeteer-extra/issues/375

While debugging/profiling I noticed that this library keeps a reference to every page in a Map(), this is were the leak was. I know that you expose a public method for removing it from the Map, so I think it's the puppeteer-extra responsibility to properly call the life cycle methods, so this is why I reported it there first.

But while I was debugging looking at the dist files, this is how it looks like:
![img](https://user-images.githubusercontent.com/3372598/99575725-c8d3a680-29b7-11eb-85e4-a4e20be1281e.png)

My first instinct was to change it to a [WeakMap](https://tc39.es/ecma262/#sec-weakmap-objects), and it in fact solved the memory leak.

My question is, is it really necessary for you to keep a strong reference to the page object?

**Comment by victornpb** [comment]
I noticed that you declared this.contexts a <WeakMap> type, but you created a `new Map()` not a `new WeakMap()`.
https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L106

Is this intentional?

**Comment by remusao** [comment]
Hey @victornpb,

Thanks for taking the time to investigate the issue. I will double-check but this looks like a bug at first glance. Pretty sure the intent was to use a `WeakMap` there. Will look into it and push a fix.

**Comment by remusao** [comment]
Hi @victornpb,

The fix has been released as part of [v1.18.6](https://github.com/cliqz-oss/adblocker/releases/tag/v1.18.6). Let me know how this goes.

**Comment by berstend** [comment]
Fix released as `puppeteer-extra-plugin-adblocker@2.11.9`
thanks @remusao @victornpb 👍
