### ISSUE TITLE
Request Interception is not enabled

### ISSUE THREAD

**Issue by jef** [cliqz-oss/adblocker#1495]
### Description

Related: https://github.com/jef/streetmerchant/issues/826

![image](https://user-images.githubusercontent.com/12074633/101514141-f377a600-394a-11eb-9060-c24823de8a63.png)

> So it seems like it's a problem with the adblocker dependency. Adding this.page.removeListener('request', this.onRequest); to the adblocker code fixed my problem as well. Not sure what is happening since I'm not an expert on Puppeteer. I'm guessing that promise doesn't resolve and so when request interception is done later on in the code base it errors out. A ticket should probably be filed.
>
> @howdoicomputer

**Comment by remusao** [comment]
Hey @jef,

Thanks for taking the time to open an issue here. I skimmed through the original issue and it was not clear how I could reproduce the issue easily on my side. I see that `streetmerchant` uses the adblocker through the `puppeteer-extra` plugin and has some logic on top to enable/disable it as well as register custom listeners. I can have a look at the issue but I would need some reasonably small script to reproduce the issue on my side if possible.

Best,
Rémi

**Comment by howdoicomputer** [comment]
Also, the `removeListener` function call was a false positive; seems to have broken after a bit.

**Comment by jef** [comment]
I'm sorry @remusao, this was an easy fix -- and silly on my part not to look into it.

Puppeteer looks to allow for request interceptions and we hadn't enabled it.

https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pagesetrequestinterceptionvalue

Going to close this out. Thanks for your time and your thoughtful input.

**Comment by remusao** [comment]
Hey @jef,

I'm glad you found the root cause. No worries at all, I'm happy to help,

Best,
Rémi
