### ISSUE TITLE
Does it support blocking popups? 

### ISSUE THREAD

**Issue by eerkaijun** [cliqz-oss/adblocker#1617]
Hi, great project here! I'm wondering if this library support blocking popups (eg: cookie popups), other than just ad and tracking? I tried embedding the library in my extension background script but it seems like it doesn't stop the popups?

**Comment by remusao** [comment]
Hi @eerkaijun,

Yes it should be able to handle these popups if you enable the annoyances as well (this can be done with `WebExtensionBlocker.fromPrebuiltFull(...)`). Can you maybe share a bit more details about how you integrated the adblocker into your background script?

**Comment by eerkaijun** [comment]
This is the embedded code in my background script. 

```
import { WebExtensionBlocker } from '@cliqz/adblocker-webextension';

WebExtensionBlocker.fromPrebuiltAdsAndTracking().then((blocker) => {
  blocker.enableBlockingInBrowser(browser);
});
```

So I assume I should use fromPrebuiltFull instead of fromPrebuiltAdsAndTracking?

**Comment by remusao** [comment]
> So I assume I should use fromPrebuiltFull instead of fromPrebuiltAdsAndTracking?

Yes exactly. I think it should be enough to handle most cases, but you might also want to add a content script to your extension as well like this: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-webextension-example/content-script.ts#L18

This is required to handle some cases of ads and popups.

**Comment by eerkaijun** [comment]
Unfortunately it still doesn't work for my case. I've added the following in background and content script respectively, but it couldn't stop the cookie consent popup on website. 

Background script: 
```
import { WebExtensionBlocker } from '@cliqz/adblocker-webextension';
import { browser } from 'webextension-polyfill-ts';

async function blockCookie() {
    const blocker = await WebExtensionBlocker.fromLists(fetch, [
        'https://www.fanboy.co.nz/fanboy-cookiemonster.txt'
    ]);
    blocker.enableBlockingInBrowser(browser);
    console.log("Blocker enabled");
};

blockCookie();
```

Content script: 
```
import { injectCosmetics } from '@cliqz/adblocker-webextension-cosmetics';
injectCosmetics(window, true);
```

PS: I've also tried 
```
import { WebExtensionBlocker } from '@cliqz/adblocker-webextension';
WebExtensionBlocker.fromPrebuiltAdsAndTracking().then((blocker) => {
  blocker.enableBlockingInBrowser(browser);
});``` 
but it didn't work for me either.

**Comment by remusao** [comment]
I see. Would you maybe be able to share the page where the popup is not blocked so that I can have a closer look?

**Comment by eerkaijun** [comment]
I am not sure what is wrong but it didn't work for all websites for me. 

I tried a few such as 
https://amp.dev/
https://www.rightmove.co.uk/
https://www.paypal.com/uk/home

**Comment by remusao** [comment]
@eerkaijun I could not reproduce on any of these sites using the sample extension from this sub-project: https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-webextension-example

Hiding of popups seems to work fine. Can you maybe compare with your own extension to identify what might be different?

**Comment by eerkaijun** [comment]
Sure, I tried out the sample extension and it works for me as well. 

Is there any way to only hide the consent popups but not block ads and tracking?

**Comment by remusao** [comment]
Yes it should be possible. I would suggest to try and enable the content blocker in the following way:
```javascript
WebExtensionBlocker.fromLists(fetch, [
  "https://raw.githubusercontent.com/cliqz-oss/adblocker/master/packages/adblocker/assets/ublock-origin/annoyances.txt",
  "https://raw.githubusercontent.com/cliqz-oss/adblocker/master/packages/adblocker/assets/easylist/easylist-cookie.txt",
]).then((blocker) => {
  blocker.enableBlockingInBrowser(browser);
});
```

This should mostly only hide popups.

**Comment by eerkaijun** [comment]
Hi @remusao, thanks for your help so far, it's been really useful. 

So I've been trying to figure out why it doesn't work on my own extension. I compare it with the sample extension, and when I open up a console for the background script, the difference is as follows: 

In the sample extension, this part of code successfully detected 'request-blocked' and therefore is shown in the console logging (for eg: block https://cdn.ampproject.org/v0/amp-consent-0.1.js)
```
blocker.on('request-blocked', (request: Request, result: BlockingResponse) => {
    incrementBlockedCounter(request, result);
    console.log('block', request.url);
  });
```

However, in my extension, nothing is detected hence nothing is shown on the console. Any ideas what could be the reason for not detecting 'request-blocked'? 

So I also looked at the difference of manifest.json and I notice that webRequest and webRequestBlocking is defined in permissions. Is that possible that this is the reason? However, I have some issues providing permission to the webRequest API as it says "webRequest API cannot be used at event page".

**Comment by remusao** [comment]
I see, this is most likely the reason. Is your extension for upcoming Manifest v3 (Chrome) or Firefox (or both)? Currently the library relies on webRequest API being available and will probably not play well with another context. Maybe you can tell me more about the architecture of the extension you are building?

**Comment by eerkaijun** [comment]
I am using Manifest v2 for chrome.

**Comment by remusao** [comment]
On the other hand, if you're only blocking popups, it might work well enough assuming your extension has the `tabs`, `http://*/*`, and `https://*/*` so that the adblocker can inject custom styles to hide those.

**Comment by eerkaijun** [comment]
Hi @remusao, yes, that seems to be the problem! I added `tabs`, `http://*/*` and `https://*/*` and now it seems to be working fine :) 

Thank you so much for being so helpful! Really appreciate it :)

**Comment by remusao** [comment]
My pleasure @eerkaijun. Happy to know that it works now!

**Comment by remusao** [comment]
@eerkaijun Small extra thought. Since you're not using the network filtering part of the blocker for your extension, you can save memory and initialization time by creating the instance using the following config:
```javascript
WebExtensionBlocker.fromLists(fetch, [
  "https://raw.githubusercontent.com/cliqz-oss/adblocker/master/packages/adblocker/assets/ublock-origin/annoyances.txt",
  "https://raw.githubusercontent.com/cliqz-oss/adblocker/master/packages/adblocker/assets/easylist/easylist-cookie.txt",
], {
  loadNetworkFilters: false, // <<< NEW
}).then((blocker) => {
  blocker.enableBlockingInBrowser(browser);
});
```

**Comment by eerkaijun** [comment]
I see, sure I will do that. Thanks again for being so helpful :)
