### ISSUE TITLE
Support for puppeteer 7.x

### ISSUE THREAD

**Issue by TimotheeJeannin** [cliqz-oss/adblocker#1674]
I looks the package `adblocker-puppeteer` does not support the latest versions of puppeteer. 
Would it be possible to add support for the latest puppeteer versions ? 

Let me know if there is anything I can do to help! :)

**Comment by remusao** [comment]
Hey @TimotheeJeannin,

I have opened #1677 to bump the version of Puppeteer used internally and as peer dependency. I had not noticed the latest releases, thanks for notifying me! If you have a minute, could you maybe have a look at the PR? That would be greatly appreciated.

Best,
Rémi
