### ISSUE TITLE
How to use with @cliqz/adblocker

### ISSUE THREAD

**Issue by chentogit** [cliqz-oss/adblocker#1730]
Hi, I'm having some problems using the @cliqz/adblocker library

```
import { FiltersEngine } from '@cliqz/adblocker';
engine = await FiltersEngine.fromLists(fetch, [
 'https://easylist-downloads.adblockplus.org/easylistchina.txt'
]);
```
When I have initialized the engine in the above way，and use the following method to match the request
```
import { Request } from '@cliqz/adblocker';

const { match } = engine.match(Request.fromRawDetails({
  type: 'script',
  url: 'https://domain.com/ads.js',
}));
```
For example, if I search for anything in Bing search, it always returns "match: true."
I don't know if there is something wrong with the way I use it. How can I tell whether to disconnect a request or hide a tag?

```
2021-03-03 11:03:51.784680+0800 ADTestFilter[31569:1665496] [javascript] https://www.bing.com/search?q=2315&qs=AS&pq=23&sk=PRES1AS1&sc=5-2&cvid=8743CF7AD0A44060A6574F3A2D6C94D7&FORM=QBLH&sp=2
2021-03-03 11:03:51.785170+0800 ADTestFilter[31569:1665496] [javascript] { exception: undefined,
  filter: 
   { csp: undefined,
     filter: undefined,
     hostname: undefined,
     mask: 65535,
     domains: 
      { entities: undefined,
        hostnames: undefined,
        notEntities: undefined,
        notHostnames: undefined },
     denyallow: undefined,
     redirect: undefined,
     rawLine: undefined,
     id: undefined,
     regex: undefined },
  match: true,
  redirect: undefined }
```

**Comment by remusao** [comment]
Hi @chentogit,

Are you using the adblocker in an extension, electron, puppeteer or another environment? In case it's one of the three first I would recommend checking the following specialized packages which will allow you to integrate the adblocker in a simple way:

* https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-electron
* https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-puppeteer
* https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-webextension

If that does not work, can you please provide a bit more context about how you want to use the adblocker library?

Best,
