### ISSUE TITLE
Usage with tauri?

### ISSUE THREAD

**Issue by Milo123459** [cliqz-oss/adblocker#1758]
How can I use this with tauri? Or, just a plugin for Tauri.

**Comment by remusao** [comment]
Hi @Milo123459,

I am not familiar with the Tauri project and `@cliqz/adblocker` has currently no support for it. But if there is a way to make it work I'm be happy to have some external contribution.

**Comment by Milo123459** [comment]
Try joining their [Discord](https://discord.com/invite/SpmNs4S)

**Comment by remusao** [comment]
At this point I don't have the bandwidth to push major new features to the project, but as I said I'm happy to receive outside contributions to add support to the Tauri project (or others).
