### ISSUE TITLE
Main_frame request treated as third-party due to initiator/originUrl field

### ISSUE THREAD

**Issue by eugenioemmolo** [cliqz-oss/adblocker#1797]
Package involved: WebExtenstion Adblocker
User Agent: Chrome 89.0.4389.90, Firefox 86.0.1

Within `webRequest.onBeforeRequest` callback context, I noticed that a `main_frame` request is flagged as third-party if the `initiator/originUrl` field is defined and its domain does not match the domain extracted from the request URL.

To clarify the scenario:

```javascript
  // Defining details as:
  const details = {
    frameId: 0
    initiator: "https://example.com" // chrome case, "originUrl" if Firefox
    method: "GET"
    parentFrameId: -1
    requestId: "1"
    tabId: 1
    timeStamp: 1234
    type: "main_frame"
    url: "https://www.github.com/"
  }
  
  const request = fromWebRequestDetails(details);
  
  // request content would be:
  {
    domain: "github.com"
    entityHashes: undefined
    hostname: "www.github.com"
    hostnameHashes: undefined
    id: "1"
    isFirstParty: false
    isHttp: false
    isHttps: true
    isSupported: true
    isThirdParty: true  // because 'example.com' !== 'github.com'
    [...]
  }
```

**Comment by remusao** [comment]
Hi @eugenioemmolo,

Thanks for opening an issue. I think it might make sense to not consider `main_frame` requests as being third-party from this function: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker/src/request.ts#L187. What do you think? Would you be willing to make a pull request with the change? I am unfortunately not able to spend a lot of time on this at the moment.

Best,
Rémi

**Comment by eugenioemmolo** [comment]
Hi @remusao,

Thank you for your quick reply. It is fine for me to contribute to the development of this great library.
I agree with your suggestion, I think the function you mentioned could always consider `main_frame` requests as being first-party.
I'll make a pull request with the change.

Regards
Eugenio

**Comment by remusao** [comment]
Thanks again @eugenioemmolo, the fix is released as part of https://github.com/cliqz-oss/adblocker/releases/tag/v1.20.4

**Comment by eugenioemmolo** [comment]
Thank you @remusao for the speedy review and release. Very glad to have given a little contribution :).
Best,
Eugenio
