### ISSUE TITLE
disableBlockingInPage is not complete

### ISSUE THREAD

**Issue by kmosunoff** [cliqz-oss/adblocker#1893]
Hello guys, thank you for such a pretty and efficient tool!

Nevertheless, I found out that the ```disableBlockingInPage``` method in ```PuppeteerBlocker``` does not disable blocking completely. To be precise, it does not remove the ```"domcontentloaded"``` listener set in the ```enable``` method of the ```BlockingContext``` class.

This leads to styles injection even after blocking disabling. Here is a couple of simple steps to reproduce the issue:
```
await puppeteerBlocker.enableBlockingInPage(page);
await page.goto(...);
const contentWithoutAds = await page.content();
await puppeteerBlocker.disableBlockingInPage(page);
await page.goto(...);
const content = await page.content();
```
You might notice that the ```content``` and the ```contentWithoutAds``` both have cosmetic styles injected. However, I expect the ```content``` to be not affected by the blocker at all. Is it a bug or a feature? :)
Thanks in advance!

**Comment by remusao** [comment]
Hey @kmosunoff,

Good catch! This definitely looks like a bug. Would you be willing to contribute a patch for this issue? I'd gladly review and publish an update of the package.

Best,
Rémi

**Comment by kmosunoff** [comment]
Sure!
I've coded a bit, could you take a look please?
https://github.com/cliqz-oss/adblocker/pull/1903
