### ISSUE TITLE
Beginner: How to create "FiltersEngine" instance if I have several list URLs and also single additional local list file?

### ISSUE THREAD

**Issue by martinrotter** [cliqz-oss/adblocker#1901]
I have several remote list URLs like:

  'https://easylist.to/easylist/easylist.txt',
  'https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt'

so I use this to create engine:

```
adblock.FiltersEngine.fromLists(fetch, [
  'https://easylist.to/easylist/easylist.txt',
  'https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt',
]).then(function (res) { engine = res; });
```

How to add one more list which I have stored in local file? I know there is `const engine = FiltersEngine.parse(fs.readFileSync('easylist.txt', 'utf-8'));` but how to combine both aspects together?

Sorry, I am node/js beginner. I plan to [integrate](https://github.com/martinrotter/rssguard/issues/410) this great project withing RSS Guard - feed reader used by thousands of users.

**Comment by remusao** [comment]
Hi @martinrotter,

Thanks for your interest. I think the easiest way to achieve this at the moment is to use the `updateFromDiff` method available on instance of `FiltersEngine`; it can add new filters (expressed as arrays of strings, and remove existing ones from the engine as well). Here is how it could look like with a self-contained example:

```js
const adblock = require("@cliqz/adblocker");
const fetch = require("node-fetch");
const fs = require("fs");

(async () => {
  const engine = await adblock.FiltersEngine.fromLists(fetch, [
    "https://easylist.to/easylist/easylist.txt",
    "https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt",
  ]);

  // Before update
  console.log(engine.getFilters().networkFilters.length);

  engine.updateFromDiff({
    added: fs.readFileSync("./custom.txt", "utf-8").split("\n"),
  });

  // Afer update
  console.log(engine.getFilters().networkFilters.length);
})();
```

And content of `custom.txt` would contain one rule (a.k.a. filter) per line:
```txt
||example.com^
||foo.com^
```

I hope this helps,
Best,
Rémi

**Comment by martinrotter** [comment]
@remusao Thanks for hints, will work best way for me out.

**Comment by remusao** [comment]
Closing this as it seems you managed to integrate the adblocker into your project. Feel free to reopen if you have any question.
