### ISSUE TITLE
Promises from injectScriptletsIntoFrame not using Promise.all

### ISSUE THREAD

**Issue by tommulkins** [cliqz-oss/adblocker#2005]
As of version 1.22.1 of adblocker-playwright @ line 289 in `adblocker-playwright/dist/cjs/adblocker.js` and `adblocker-playwright/dist/es6/adblocker.js` the `await promises` should probably be replaced with 
```
  await Promise.all(promises);
```

This appears to have been a problem in the past for both `cjs` and `es6` versions in puppeteer.  See https://github.com/cliqz-oss/adblocker/issues/1060

**Comment by remusao** [comment]
Hi @tommulkins,

Good catch, this was fixed on puppeteer but not playwright. Would you be willing to open a PR with a fix? I'd be happy to review and publish it.

Best,
Rémi

**Comment by tommulkins** [comment]
Thanks Rémi.  My PR is ready at https://github.com/cliqz-oss/adblocker/pull/2006

**Comment by remusao** [comment]
Thanks for your contribution! The fix has been released: https://github.com/cliqz-oss/adblocker/releases/tag/v1.22.2
