### ISSUE TITLE
ad blocking not working

### ISSUE THREAD

**Issue by grinono** [cliqz-oss/adblocker#2158]
I was just checking the firefox browser extension. But if I load a [webpage](https://www.nu.nl/) with crazy lot of banners. it does not block anything. Is it correct that is blocker does not work for this page?

Ghostery does bock the banners just fine.

**Comment by remusao** [comment]
Can you specify which Firefox browser extension you checked?

**Comment by grinono** [comment]
[cliqz example extension](https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-webextension-example)

**Comment by remusao** [comment]
Thanks, I will have to check but as far as I know it should work. There might be a bug, though. Does it seem to block ads on other websites? Or only this one in particular?

**Comment by grinono** [comment]
i checked some other pages. But got the same result. sure extension console message

```
Webconsole context has changed
Error: Can't find profile directory. XULStore.jsm:66:15
Webconsole context has changed
Uncaught ReferenceError: require$$1 is not defined
    <anonymous> moz-extension://f9458467-1c1b-134b-9d6d-54718ea6a5dd/dist/background.iife.js:1354
background.iife.js:1354:1

​```

**Comment by remusao** [comment]
I could not reproduce so far, which version of Firefox are you using locally for your testing? Could you maybe try with Chrome as well?

**Comment by grinono** [comment]
I'm on Firefox version 91.0. Same result when starting the extension with Chrome. any other suggestion on where to look? I can share a zip file of the extension. Or maybe you have one that i can test?

**Comment by grinono** [comment]
investigated a bit further, i missed the requirement for ```yarn bundle```. After having the engine.bin generated it works as expected.

**Comment by remusao** [comment]
Interesting, so the extension was trying to load something else instead of the expected bundle?
