### ISSUE TITLE
blocking YouTube ads

### ISSUE THREAD

**Issue by grinono** [cliqz-oss/adblocker#2176]
I saw YouTube video prerolls are not blocked. What is the best process for doing this? I was thinking about adding an other opensource engine for just that. Any suggestions?

**Comment by remusao** [comment]
Hi @grinono,

I tried to reproduce but could not (using the webextension-example demo folder). Could you try again and confirm that you are still seeing preroll ads? It could be that some filters have been updated since then.

Best,

**Comment by grinono** [comment]
yes, i'm seeing the youtube pre-rolls. still. prob, some youtube updates i guess. i will integrate some other youtube ads blocking scripts to resolve the issue.
