### ISSUE TITLE
Request is already handled!

### ISSUE THREAD

**Issue by Kikobeats** [cliqz-oss/adblocker#2213]
Hello,

I recently shipped some wapping about using a puppeteer with the ability to proxy requests to an external service:

https://github.com/microlinkhq/browserless/blob/master/packages/browserless/src/index.js#L121
https://github.com/microlinkhq/browserless/blob/master/packages/browserless/src/index.js#L20

Essentially it's performing the requests using an HTTP client and forwarding the request back to the browser.

Probably I'm doing something wrong there because it's causing some conflicts with the adblocker.

The adblocker is declared here:
https://github.com/microlinkhq/browserless/blob/master/packages/goto/src/index.js#L181

The proxy handling is declared before. So I think the thing happening there is, although the request was resolved by the proxy,  still, it's registered at least in a way the adblock is retrieving it but it throws an error because the request was already resolved.

This is the error trace:

```
  agent-base Resolving socket for 'https:' request: 'GET /en_US/sdk.js?hash=ce62705608d29d6b3e7f82da122e8dac' +2s
  socks-proxy-agent Creating socks proxy connection: { proxy: { host: 'socks.myproxyserver.com', port: 8888, type: 5 }, destination: { host: '157.240.241.1', port: 443 }, command: 'connect', timeout: undefined } +2s Error
Sep 6 23:34:26   socks-proxy-agent Successfully created socks proxy connection +341ms
Sep 6 23:34:28 Error: Request is already handled!
    at Object.assert (/home/node/app/node_modules/puppeteer/src/common/assert.ts:23:21)
    at HTTPRequest.continue (/home/node/app/node_modules/puppeteer/src/common/HTTPRequest.ts:394:5)
    at PuppeteerBlocker.onRequest (/home/node/app/node_modules/@cliqz/adblocker-puppeteer/adblocker.ts:317:23)
    at BlockingContext.onRequest (/home/node/app/node_modules/@cliqz/adblocker-puppeteer/adblocker.ts:64:43)
    at /home/node/app/node_modules/puppeteer/src/common/Page.ts:630:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HTTPRequest.finalizeInterceptions (/home/node/app/node_modules/puppeteer/src/common/HTTPRequest.ts:228:5)
```

is it a proper way I can avoid this error? in the worst of scenario, I can disable the adblocker if I'm using a proxy server, but could be nice to find a sweet spot to use both things 🙂

**Comment by remusao** [comment]
Hi @Kikobeats,

Thanks for reaching out. I think the issue is that if you call [`respond` here](https://github.com/microlinkhq/browserless/blob/master/packages/browserless/src/index.js#L32) then puppeteer considers the request was already handled and you cannot modify it anymore. So I guess you would need to use some kind of request pipeline, or integrate the adblocker directly in your proxy function to apply the blocking there (maybe even before you make the HTTP request).

Best,

**Comment by Kikobeats** [comment]
yea you're right, definitely it could be better on my side, merging all the page requests in a single place.

Also I noted [page.respond](https://github.com/puppeteer/puppeteer/blob/v10.2.0/docs/api.md#httprequestrespondresponse-priority)  allows to adjust priority level, that could be a thing to consider as well

**Comment by remusao** [comment]
> yea you're right, definitely it could be better on my side, merging all the page requests in a single place.
> 
> Also I noted [page.respond](https://github.com/puppeteer/puppeteer/blob/v10.2.0/docs/api.md#httprequestrespondresponse-priority) allows to adjust priority level, that could be a thing to consider as well

Ha yes, true, that's a new change in puppeteer which allows multiple handlers I think. There might be some option to enable this behavior.

I think this might be relevant: https://github.com/puppeteer/puppeteer/blob/v10.2.0/docs/api.md#cooperative-intercept-mode-and-legacy-intercept-mode

**Comment by Kikobeats** [comment]
Hey, @remusao this is no more an issue to me since I found an elegant way to provide a proxy using Chrome arguments:

```
args: args.concat(`--proxy-server=${opts.proxy.toString()}`)
```

In that way Chrome handles the proxy logic, without the necessity to ship extra code there 🙂

**Comment by remusao** [comment]
Perfect @Kikobeats! Happy you found a way forward.
