### ISSUE TITLE
Puppeteer: Upgrade to Cooperative Mode

### ISSUE THREAD

**Issue by akornatskyy** [cliqz-oss/adblocker#2277]
See [here](https://github.com/puppeteer/puppeteer/blob/v10.2.0/docs/api.md#upgrading-to-cooperative-mode-for-package-maintainers).

**Comment by remusao** [comment]
Hey @akornatskyy,

This makes sense, thanks for pointing it out. Would you have some bandwidth to open a PR addressing this issue? I'd be happy to review and release this change.

Best,
Rémi

**Comment by remusao** [comment]
Released: https://github.com/cliqz-oss/adblocker/releases/tag/v1.23.0

Thanks for contributing this improvement!
