### ISSUE TITLE
adblocker-electron missing cjs build

### ISSUE THREAD

**Issue by char101** [cliqz-oss/adblocker#242]
Hi,

There is no `dist/cjs/adblocker.js` in the npm package as specified in package.json `main` field. `adblocker-electron` version is 0.12.0.

**Comment by char101** [comment]
Apparently the path in [`rollup.config.ts`](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-electron/rollup.config.ts#L17) does not match with the path in `package.json`

**Comment by remusao** [comment]
Hi @char101!

I could confirm this issue, I will be fixing this later today as well. Thanks again for taking the time to opening the issues today, that is very helpful.

Best,
Rémi

**Comment by char101** [comment]
Thanks for confirming the issue.

To clarify there are two missing files (1) the preload script in `cjs/preload.js` and (2) the module entry point in `cjs/adblock.js`.

**Comment by char101** [comment]
Thank you.
