### ISSUE TITLE
adblocker-electron: constructor should pass arguments to super

### ISSUE THREAD

**Issue by char101** [cliqz-oss/adblocker#246]
Otherwise the inherited `parse` static method is useless because it calls the parent constructor with the filters config.

**Comment by remusao** [comment]
Hi again @char101,

Good point, the interface for all blockers should be unified, which means we should be able to pass all options to the ElectronBlocker class. I will be pushing a fix for this later today.

Thanks,
Rémi

**Comment by char101** [comment]
Hi, other than the options, the result from parsing the filters is passed via the [constructor](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker/src/engine/engine.ts#L34), so it is really necessary for the proper functioning of the `parse` method.

**Comment by remusao** [comment]
This should be fixed with #248

**Comment by char101** [comment]
Thank you.
