### ISSUE TITLE
adblock-electron: events on content blocking

### ISSUE THREAD

**Issue by char101** [cliqz-oss/adblocker#247]
Hi,

Would it be possible to emit some events in the case of a matched redirect/blocked url?

Having some events emitted will be useful to verify that the blocking works, otherwise there is no way to verify it.

Thanks.

**Comment by remusao** [comment]
Hi,

Yes definitely, this is a planned feature for next release. There is an issue tracking discussions for this: https://github.com/cliqz-oss/adblocker/issues/80

Best,
Rémi
