### ISSUE TITLE
personalized lists doesn't have blocker instance

### ISSUE THREAD

**Issue by Truth1984** [cliqz-oss/adblocker#341]
In order to use PuppeteerBlocker, we need to use
`blocker.enableBlockingInPage(page)` on the page.

However, I can only get such blocker instance by using `fromPrebuiltAdsAndTracking` and `fromPrebuiltAdsOnly`.

I have few duplicated list like **easylist**; so parsing my list and fetching your `fromPrebuiltAdsAndTracking` is redundant ?

Thus, is there any other way to use only personalized list for the page ?

**Comment by remusao** [comment]
Hi @Truth1984,

Thanks for reaching out! There are two ways you can avoid using the `fromPrebuilt` helpers if you already know which lists you want. The first one can be used if you already fetched the lists in their raw string form, in which can you can use `PuppeteerBlocker.parse(myLists)` where first argument is a string containing all the rules you want to add (in the EasyList format):

```typescript
import { PuppeteerBlocker } from '@cliqz/adblocker-puppeteer';

let blocker = PuppeteerBlocker.parse(```
filter1
filter2
```);

// Or
blocker = PuppeteerBlocker.parse(fs.readFileSync('easylist.txt', 'utf8'));

// Or
blocker = PuppeteerBlocker.parse([
  fs.readFileSync('easylist.txt', 'utf8'),
  fs.readFileSync('easyprivacy.txt', 'utf8'),
].join('\n')); // all lists need to be merged into one string
```

You can also ask `PuppeteerBlocker` to fetch the lists for you:
```typescript
import { PuppeteerBlocker } from '@cliqz/adblocker-puppeteer';
import fetch from 'node-fetch';

const blocker = await PuppeteerBlocker.fromLists(fetch, [
  'https://easylist.to/easylist/easylist.txt',
  'https://easylist.to/easylist/easyprivacy.txt',
]);
```

I hope that helps!
Rémi

**Comment by Truth1984** [comment]
Thanks, I was using `list.map(value=> PuppeteerBlocker.parse(......))`

**Comment by remusao** [comment]
> Thanks, I was using `list.map(value=> PuppeteerBlocker.parse(......))`

I see. The only issue is that you get multiple blockers then! Let me know how the other approach works for you.

**Comment by Truth1984** [comment]
Thank you very much, they worked.
