### ISSUE TITLE
Error fetching latest version of uBlock resources

### ISSUE THREAD

**Issue by Kikobeats** [cliqz-oss/adblocker#372]
Hello,

When I perform a `npm install`, I'm getting the following error trace on my terminal:

<img width="1058" alt="Screenshot 2019-10-09 at 10 47 08" src="https://user-images.githubusercontent.com/2096101/66470373-c0f1c500-ea89-11e9-83a0-6d064c87b59f.png">

After checking the code, the thing is related to

https://github.com/cliqz-oss/adblocker/blob/c2973c0427cab873447d2806805b88dc1eabba56/packages/adblocker/src/fetch.ts#L64

where the code is expecting a `latestRevision` field from [`metadata.json`](https://cdn.cliqz.com/adblocker/resources/ublock-resources/metadata.json) but looks like this JSON has changed and now it returns an array or revisions.

I suppose the code there is outdated and needs to be updated to pick the first revision from the array? not sure about that.

**Comment by remusao** [comment]
Hi @Kikobeats,

Yes there is some issue indeed, I'm making a fix now and will push a release in the next hour. Thanks for letting me know and sorry for the breakage. We've released a new version of our filters builder yesterday evening and I did not anticipate this particular breaking change.

**Comment by remusao** [comment]
@Kikobeats release [v1.3.1](https://www.npmjs.com/package/@cliqz/adblocker-puppeteer) should fix this issue.

**Comment by Kikobeats** [comment]
No problem! I can confirm now is working fine 🙂
