### ISSUE TITLE
Ad not blocked on thelocal.ch

### ISSUE THREAD

**Issue by ghost** [cliqz-oss/adblocker#395]
Sponsored content not blocked

![Captura de Pantalla 2019-11-30 a la(s) 22 09 19](https://user-images.githubusercontent.com/57176665/69907981-d8c93380-13be-11ea-9344-e51c8aca353e.png)

CSS rules that can fix this:

.promo-module

I am not familiar with how Cliqz AdBlocker processes rules here but in AdGuard this rule is also necessary:

thelocal.ch#?#body > div > .section:has( > div[class]:contains(Sponsored))

**Comment by remusao** [comment]
@Lucas-Di-Tomase thanks a lot for your report and the suggestion of filter addition. The second one seems needed but at the moment Cliqz does not support this particular kind of filter (procedural filters). I have started the work of implementing them but did not get the time to polish it yet. I will check if this can be blocked differently in the meanwhile!
