### ISSUE TITLE
[adblocker-electron] preload.js missing in dist_electron

### ISSUE THREAD

**Issue by theMK2k** [cliqz-oss/adblocker#398]
Hi,

I successfully integrated and use @cliqz/adblocker-electron, however electron's debug console shows the following errors:

Unable to load preload script: path/to/dist_electron/preload.js

Error: Cannot find module 'path/to/dist_electron/preload.js'
Require stack:
- path/to/dist/resources/electron.asar/renderer/init.js

Even with these errors, the adblocking functionality seems to work fine.

However, I'd like to know if I did something wrong or miss something in my setup.

The preload.js script can be found in node_modules/@cliqz/adblocker-electron/dist/cjs/ or node_modules/@cliqz/adblocker-electron/dist/es6/.

I can manually copy it over to path/to/dist_electron/, but this only fixes for locally serving the electron app, electron build would still be affected, as it is missing the file in the .asar file.

Any hints? 😄

**Comment by remusao** [comment]
Hi @theMK2k,

Apologies for answering so late. Could you maybe give me more details about your setup? Currently the `adblocker.js` bundle from `@cliqz/adblocker-electron` makes the assumption that `preload.js` is in the same folder. This means that bundling the code with the rest of your application might break the behavior. On the other hand I am not sure how to do it differently at the moment. One way to fix it in your case would be to copy the `preload.js` file as part of your build process.

The network filtering (which does the heavy lifting of blocking ads) will not be impacted by this breakage, but a few features will not work (e.g.: cosmetics).

Best,
Rémi

**Comment by theMK2k** [comment]
Hi @remusao,

I just invited you to my currently private repo - maybe you can have a look around?

If I remember correctly:

1. I npm installed @cliqz/adblocker-electron
2. I implemented the adblocker in src/background.js (which is used by vue-cli-plugin-electron-builder and instantiates app, Browserwindow etc. from electron too.

**Comment by remusao** [comment]
@theMK2k, I see. I am not very familiar with the way `vue` is bundling source code, but I assume that the code from all your source files is bundled into one final one and put in some output folder. Do you think you could try to copy the `preload.js` script in this same output folder and see if it solves the issue?

**Comment by theMK2k** [comment]
Thanks, I'll look into that. It probably is more an electron bundling issue (.asar file) than vue bundling (webpack).

**Comment by remusao** [comment]
Sounds good. If you know of any other way we could bundle the `preload.js` script, I'm happy to make some changes in the package to make your life easier!

**Comment by hurshagrawal** [comment]
To anyone else facing this issue, as mentioned above this is because the `preload.js` uses `require("@cliqz/adblocker-content");` to pull in the `adblocker-content` library. Because of the way Electron packages asar bundles, this means in production that `require` doesn't resolve properly.

The workaround for us was to package that preload via webpack/browserify first, then after calling `blocker.enableBlockingInSession(session);`, removing the preload injected by the adblocker from the session and injecting our own, custom, webpack-bundled preload.

@remusao Thanks for an incredible library! And for creating the Electron plugin. It works beautifully otherwise! If you do want to make it work better with Electron, one possible fix would be to run the preload through Browserify/Webpack/Parcel to resolve the requires inline.

**Comment by remusao** [comment]
@hurshagrawal thank you for the kind words. What a coincidence, I pushed a change yesterday to bundle the preload script after I noticed some issue while testing adblocker-electron locally. I will  releasing a new version soon (maybe today). When it’s out, could you maybe tell me if it solves the issue you had? (The work-around of bundling it yourself should not be needed anymore).

**Comment by remusao** [comment]
@hurshagrawal @theMK2k I have released `v1.6.3` today with the mentioned improvements. Please let me know if it improves your workflow, or if further changes would be needed to make the adblocker integrate smoothly into your projects.

**Comment by hurshagrawal** [comment]
@remusao thanks so much! Will try it out and report back.

**Comment by hurshagrawal** [comment]
Works great! Thanks so much! And thanks for all your hard work on this library.

**Comment by theMK2k** [comment]
Thanks alot, the errors are gone!
