### ISSUE TITLE
9to5mac is broken with Ghostery enabled

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [cliqz-oss/adblocker#455]
https://9to5mac.com/ is broken with the Ghostery extension enabled

Although ads are blocked I cant scroll through the website passed certain point so the website is broken

**Comment by remusao** [comment]
Thanks for the report @Lucas-Di-Tomase, I could reproduce and identified the issue. I need to understand why it is happening but that's an interesting side-effect of blocking ads. Will let you know when I find out more.

**Comment by Lucas-Di-Tomase** [comment]
Great! Thanks for answering so fast! I do understand that 9to5mac is quite a troublesome website so I understand that some extensions can break it

**Comment by remusao** [comment]
I found a fix and pushing it now. It will take up to a few hours to reach everyone (usually we push one update per day).

**Comment by Lucas-Di-Tomase** [comment]
Great! Thanks! I also opened other issues that I found with websites and Ghostery. I love Ghostery everyday a little more so I want to help turn it into the best privacy/adblocking tool out there

**Comment by remusao** [comment]
Thank you! I started looking into the other issues. This is very helpful.
