### ISSUE TITLE
tn.com.ar is broken with Ghostery enabled

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [cliqz-oss/adblocker#456]
If you visit any news article on this site, for example:

https://tn.com.ar/deportes/esencial/tras-furia-de-lionel-messi-barcelona-podria-despedir-eric-abidal_1031634 

you will see that towards the end of the website there are parts that are not loading. I attach screenshot

![Captura de Pantalla 2020-02-05 a la(s) 09 57 25](https://user-images.githubusercontent.com/57176665/73843803-1c487f80-47fe-11ea-87e9-65f3d6518aee.png)

**Comment by remusao** [comment]
Thanks for the report. I pushed a fix for these as well. The two big spinners are usually populated using content served by a third-party domain classified as advertiser. So I have hidden those. The bottom-left one seems to be broken even without an adblocker so I assume this is an issue with the website itself.

**Comment by Lucas-Di-Tomase** [comment]
Yeah I had the same problem with AdGuard and I found that one was the site fault. Thanks!
