### ISSUE TITLE
cnet.com is broken with Ghostery enabled

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [cliqz-oss/adblocker#462]
CNET won´t load the lower half of the website properly with Ghostery enabled

Screenshots:

![Captura de Pantalla 2020-02-05 a la(s) 11 38 53](https://user-images.githubusercontent.com/57176665/73851465-46a13980-480c-11ea-8a99-37b2e61668b2.png)

![Captura de Pantalla 2020-02-05 a la(s) 11 39 43](https://user-images.githubusercontent.com/57176665/73851472-4a34c080-480c-11ea-9b36-58f88db747d3.png)

![Captura de Pantalla 2020-02-05 a la(s) 11 40 06](https://user-images.githubusercontent.com/57176665/73851476-4c971a80-480c-11ea-88bc-4df516d57e58.png)

**Comment by remusao** [comment]
Closing as fixed. Feel free to re-open if you notice issues.
