### ISSUE TITLE
I want get the original request from puppeteer when req blocked

### ISSUE THREAD

**Issue by sheikalthaf** [cliqz-oss/adblocker#483]
I want to know the requestId from puppeteer when the req gets blocked. To get the requestId i want the original request object from puppeteer. It is possible to get the request in on event listener?

blocker.on('request-blocked', val => {
        logger.debug(`request blocked ${JSON.stringify(val.request)}`); // like this
      });

**Comment by remusao** [comment]
Hi,

Currently the Request you get in the listener is an instance of internal request representation of the adblocker (which contains mostly the same information as in the puppeteer request but is platform agnostic: it works on Electron, WebExtension, etc.) which is derived from the puppeteer request. I could not find a mention of a requestId attribute on the puppeteer request abstraction: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-request

Could you maybe point me to the information you would need? Then if it’s not exposed already I’d be happy to consider adding it.

Best,

**Comment by sheikalthaf** [comment]
You can get the `requestId = request._requestId`. It is better I can get the original request in request-blocked event.

**Comment by remusao** [comment]
With latest release you can now access the original request details like this:

```js
blocker.on('request-blocked', (request) => {
  console.log('request blocked', request._originalRequestDetails);
});
```

Let me know if that works for you,

**Comment by sheikalthaf** [comment]
Thanks for the implementation.

Working like charm. Also thanks for your awesome work in this library.

Keep up the good work 🎉👍👏
