### ISSUE TITLE
Add option to intercept the request outside of adblocker (puppeteer)

### ISSUE THREAD

**Issue by sheikalthaf** [cliqz-oss/adblocker#493]
If I use this adblocker and I also try to intercept the request and try to continue the request getting an error `error: request already handled`. e.g

```javascript
PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch).then((blocker) => {

  blocker.enableBlockingInPage(page);

});

page.on('request', interceptRequest => {
    interceptRequest.continue()
})
```

Need an option to intercept the request when request is continued internally in blocker.

**Comment by remusao** [comment]
The issue is that in interception mode, a request will be stalled until `.continue()` is called. The adblocker does not have knowledge of what is outside, and if a request will be handled by another handler or not. There could be an option for that but this does not seem satisfying. Another option could be to no use `enableBlockingInPage` for your project but register the listeners yourself. Something like:

```js
import { PuppeteerBlocker } from '@cliqz/adblocker-puppeteer';

// await page.setRequestInterception(true);

PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch).then((blocker) => {
  page.on('framenavigated', (frame) => blocker.onFrameNavigated(frame));
  page.on('request', (request) => {
    const { redirect, match } = blocker.match(fromPuppeteerDetails(request));

    if (redirect !== undefined) {
      request.respond({
        body: redirect.body,
        contentType: redirect.contentType,
      });
    } else if (match === true) {
      request.abort('blockedbyclient');
    } else {
      // ---------------------------------- //
      // TODO - do something with 'request' //
      // ---------------------------------- //
      request.continue();
    }
  });
});
```

**Comment by sheikalthaf** [comment]
Oh that's great. I really don't know about that. I don't know whether it is documented or not. If not please document it because it is one of the main advantage of this adblocker


Thanks for your support 👏

**Comment by remusao** [comment]
> Oh that's great. I really don't know about that. I don't know whether it is documented or not. If not please document it because it is one of the main advantage of this adblocker
> 
> Thanks for your support clap

The documentation could really be improved and I was thinking lately about how it should be done best. I will consider your comment for when I find time to revamp it! Thanks for the suggestion.

**Comment by sheikalthaf** [comment]
Some of the API's you mentioned is not exposed i think.

![image](https://user-images.githubusercontent.com/22526247/74506050-b1dec000-4f1e-11ea-881b-376a60a16980.png)

any reason?

**Comment by remusao** [comment]
Did you update to latest version? They were moved to another class by mistake and I reverted the change yesterday.

**Comment by sheikalthaf** [comment]
After updating to the latest version it is showing.

Thanks
