### ISSUE TITLE
fromPrebuiltAdsAndTracking is failing to get manifest

### ISSUE THREAD

**Issue by hurshagrawal** [cliqz-oss/adblocker#567]
Hi there! Thanks again for this incredible library. We're seeing the following error when using `fromPrebuiltAdsAndTracking` in our prototype electron app–

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 7RAl9ajcDvUDwg4RcjdKK7gVGsSyuZmX2sjhP-jxdl1UHVmkwRs22A==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
res ---> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: H_QzlRKBcs0r_vQxDukaNllTYfUcsZVLlkj6uOMgU6rEsdXEKldkgQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

Seems like the library does a request to `https://cdn.cliqz.com/adblocker/resources/ublock-resources/metadata.json` and gets that response. Any ideas on ways to get around this? Should we reverse proxy the request to avoid hitting the CDN too much (we only have 2-3 people using the app so likely not that?). Or does the request need some sort of headers?

Thanks so much!

**Comment by remusao** [comment]
Hi @hurshagrawal,

It seems like you might be hitting one of our rate-limiting rules (maybe by requesting too often from the same IP). If you tell me a bit more about how you currently initialize the adblocker I would be happy to give you pointers about how you can avoid hitting the CDN at all.

Best,

**Comment by hurshagrawal** [comment]
Oh sure– we're using 1.5.0. I'll update and try! Also happy to use a reverse proxy and only hit your servers once a day or something.

**Comment by AudriusKo** [comment]
Encountered same issue today, on 1.4.0. After updating to latest version it kept failing (failed downloading pre-built, fallback to fetching lists), but at least errors were handled.

**Comment by hurshagrawal** [comment]
@remusao This is so helpful, thanks so much! Sounds great– we'll both start serializing/deserializing and switch to using lists from Github.

Ah we're investigating building a new web browser and currently using Electron as a way to prototype product ideas. This repo has been incredibly helpful as a way for us to bootstrap ad and tracker blocking.

**Comment by remusao** [comment]
> Encountered same issue today, on 1.4.0. After updating to latest version it kept failing (failed downloading pre-built, fallback to fetching lists), but at least errors were handled.

Yes actually downloading the prebuilt is only meant to speed-up the operation but it should always work with the fallback. The log message is not really an error. Would caching the engine work in your use case?

**Comment by remusao** [comment]
Closing this issue as resolved. Feel free to re-open if something is not right!
