### ISSUE TITLE
Using adblocker with resourceType is causing Request is already handled! errors

### ISSUE THREAD

**Issue by leem32** [cliqz-oss/adblocker#698]
I need to block some images (jpg, gif) as well as blocking ads, but when I use the ad blocker alongside `resourceType()` i get multiple `Request is already handled!` errors and the images are not blocked.

I can use `request._interceptionHandled` to detect if the request is handled but I don't see how that helps because I need to abort these requests and they may have already been handled in a different way.

```javascript

const puppeteer = require('puppeteer-extra');
const AdblockerPlugin = require('puppeteer-extra-plugin-adblocker');

const adblocker = AdblockerPlugin({
  blockTrackers: true // default: false
});
puppeteer.use(adblocker);

...

 await page.setRequestInterception(true);

 page.on('request', request => {
      const resourceUrl = request.url().toLowerCase();

      if (request.resourceType() == 'image' && resourceUrl.indexOf('.png') === -1 && resourceUrl.indexOf('.svg') === -1 ||
          resourceUrl.indexOf('.jpg') !== -1 ||
          resourceUrl.indexOf('.gif') !== -1) {
                console.log(request._interceptionHandled);
                request.abort();
       }

      if (request.resourceType() == 'imageset' && resourceUrl.indexOf('.png') === -1 && resourceUrl.indexOf('.svg') === -1) {
          console.log(request._interceptionHandled);
          request.abort();    
      }

   request.continue();
 });

```

Are there any workarounds for this?

**Comment by remusao** [comment]
Hi @leem32,

There are two ways I can think of to go around this issue, both of which would probably be easier using the base library `@cliqz/adblocker-puppeteer` (to get more control) instead of puppeteer-extra:

1. You could make use of the adblocker engine directly in your request listener as described here: https://github.com/cliqz-oss/adblocker/issues/493#issuecomment-585873954 (might require some adjustment for your particular use case).
2. You could teach the adblocker to also block the images, which could be done by adding a few rules on top after initialization:

```js
const fetch = require('node-fetch');
const { PuppeteerBlocker } = require('@cliqz/adblocker-puppeteer');

PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch).then((blocker) => {
  // Add some rules to block images
  blocker.updateFromDiff({
    added: [
      '.jpg|$image',
      '.gif|$image',
    ],
  });
});
```

I hope that helps!

**Comment by leem32** [comment]
Thanks, I'll try the second option first.
Could I add other types to the blocker too e.g `'.webp|$image', '.mp4|$media'` for example?

**Comment by remusao** [comment]
Yes you can add filters, the `.webp|` part would mean that the URL needs to end with (that's the meaning of `|`) then you can add options to narrow down the kind of requests to block (after `$`). So `.webp|$image` means that you want to block any request of type `image` (this will also include `imageset`) with a URL ending with `.webp`. And `.mp4|$media` should also work!

**Comment by leem32** [comment]
Hi @remusao,

I may be doing something wrong, but the example failed to block images. Ads were blocked, however.

```javascript

const fetch = require('node-fetch');
const { PuppeteerBlocker } = require('@cliqz/adblocker-puppeteer');

...

// page = await browser.newPage();
// To get the first page of the current browser
page = (await browser.pages())[0];

PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch).then((blocker) => {
   // Add some rules to block images
   blocker.updateFromDiff({
      added: [
          '.jpg|$image',
          '.gif|$image',
       ],
   });
   blocker.enableBlockingInPage(page);
});

```

**Comment by remusao** [comment]
I need to check this out, can you maybe try to change `.jpg|$image` to `.jpg^$image` (same for `.gif|$image`). If there are query parameters or fragments the matching might fail because then the image prefix is not the end of the URL. This `^` means either end of URL or a separator.

**Comment by leem32** [comment]
No, that didn't work either, unfortunately. As my aim is to block adult content from screenshots I tested redtube.com and I can see the ad is blocked but none of the images are.

**Comment by remusao** [comment]
@leem32 I see what it's not working, there might be an exception preventing the adblocker from "breaking" the images from these websites (i.e. blocking the images), in this can we can override using the `important` option. I got the following working:

```js
blocker.updateFromDiff({
  added: [
    // Block all images!
    // "*$image,important,domain=redtube.com|pornhub.com",

    // Block some kinds of images
    '.png^$image,important,domain=redtube.com|pornhub.com',
    '.jpg^$image,important,domain=redtube.com|pornhub.com',
    '.webp^$image,important,domain=redtube.com|pornhub.com',
    '.gif^$image,important,domain=redtube.com|pornhub.com',
    '.svg^$image,important,domain=redtube.com|pornhub.com',

    // Block videos
    '.webm^$media,important,domain=redtube.com|pornhub.com',
    '.mp4^$media,important,domain=redtube.com|pornhub.com',
  ],
});
```

If you really want to block all images you can use the first commented filters. I have added options to only apply these rules on `redtube.com` and `pornhub.com`.

**Comment by leem32** [comment]
@remusao Do I need to update the adblock npm package for this update? npm is still on version 1.13.0.

**Comment by remusao** [comment]
No I tried locally with 1.13.0 and it worked. Not working on your side? I could send you the full version of the script otherwise.

**Comment by remusao** [comment]
Hey @leem32, did you get images blocking figured out? Happy to help if it’s not working yet.

**Comment by leem32** [comment]
Hi @remusao, No, I got the adblocker working for ads but not for images. I've done things manually by using the code I posted earlier using `resourceType` to block images and media and then to block the adult ads I just blocked the url requests.

```javascript

    // the main navigation request returns null for request.frame().parentFrame()
    // so if not null it may be an iframe request
    // this prevents the filters below blocking a website domain being checked e.g trafficjunky.com
    if (request.frame().parentFrame() != null) {

        // block ads on adult sites which are inside an iframe
        // in the future I would like to crawl iframes and abort image and media requests
        if (request.url().indexOf('trafficjunky') !== -1 || request.url().indexOf('contentabc') !== -1) {
            request.abort();
            return; // prevent calling continue after abort
        }
    }

```

I also created a dirty ad script and tracker blocker using the match method to check for certain keywords in `script` requests and aborting the matching requests.

I ended up needing to intercept `document` requests too. In order to do some basic URL manipulation and was a little worried that I was going too far outside the scope of the adblocker plugin.

Thanks for your help anyhow. I will keep a close eye on your adblocker extension with the intention of using it in the future.

All the best :)

**Comment by remusao** [comment]
Good to hear. I will close this issue then, feel free to open another one if you need anything!

Best,

**Comment by SaadEddinHassania** [comment]
> No I tried locally with 1.13.0 and it worked. Not working on your side? I could send you the full version of the script otherwise.
> 
> Edit: Here is the full script I used to test locally.
> 
> ```js
> const puppeteer = require("puppeteer");
> const fetch = require("node-fetch");
> const { PuppeteerBlocker } = require("@cliqz/adblocker-puppeteer");
> 
> (async () => {
>   const browser = await puppeteer.launch({
>     headless: false,
>     defaultViewport: null,
>   });
>   const page = await browser.newPage();
>   const blocker = await PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch);
> 
>   blocker.updateFromDiff({
>     added: [
>       // Block all images!
>       // "*$image,important,domain=redtube.com|pornhub.com",
> 
>       // Block some kinds of images
>       ".png^$image,important,domain=redtube.com|pornhub.com",
>       ".jpg^$image,important,domain=redtube.com|pornhub.com",
>       ".webp^$image,important,domain=redtube.com|pornhub.com",
>       ".gif^$image,important,domain=redtube.com|pornhub.com",
>       ".svg^$image,important,domain=redtube.com|pornhub.com",
> 
>       // Block videos
>       ".webm^$media,important,domain=redtube.com|pornhub.com",
>       ".mp4^$media,important,domain=redtube.com|pornhub.com",
>     ],
>   });
> 
>   await blocker.enableBlockingInPage(page);
> 
>   await page.goto('https://redtube.com');
> })();
> ```

How can I block images, media and styles without load them to get better performance, this way that you used loading them, but not display them (they took sometimes)
![image](https://user-images.githubusercontent.com/10339520/98453201-3d5c4900-215f-11eb-9fc9-57f823d0bed2.png)
